services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M --transaction-isolation=REPEATABLE-READ
    environment:
      cap_add: "SYS_NICE"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: open_social
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  solr:
    image: solr:8
    restart: unless-stopped
    command: bash -c "solr-precreate drupal && solr-foreground"
    ports:
      - "8983:8983"

volumes:
  database: